api:
  dashboard: false
  insecure: true
  debug: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
        - nofloc@file
      tls:
        certResolver: letsencrypt

serversTransport:
  insecureSkipVerify: true

pilot:
  dashboard: false

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: frontend
  file:
    filename: /configurations/dynamic.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: ngt@ae.ag
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
#  buypass:
#    acme:
#      email: ngt@ae.ag
#      storage: acme.json
#      caServer: https://api.buypass.com/acme/directory
#      keyType: EC256
#      httpChallenge:
#        entryPoint: web